import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';

const Home: NextPage = () => {
    return (
        <div className="flex flex-col h-screen justify-between">
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <header className="h-10 bg-red-500">Header</header>
            <main className="mb-auto h-10 bg-green-500">Content</main>
            <footer className="h-10 bg-blue-500">Footer</footer>
        </div>
    );
};

export default Home;
